version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'ln2sql'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306